Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "20190604.0.0"
  config.vm.boot_timeout = 1500
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.synced_folder "~/regal-dev", "/opt/regal/src",type: "virtualbox"
  config.vm.synced_folder ".", "/vagrant",type: "virtualbox"
  config.vm.network "private_network", ip: "192.168.50.4"

if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false  
end
  config.vm.provider "virtualbox" do |v|
     v.memory = 4096
     v.cpus = 2
     v.name = "regal-ubuntu18"
  end
end

